//another json data
const students = [
  {
    id: 1,
    first_name: "Jourdan",
    last_name: "Flores",
    email: "jflores0@pbs.org",
    gender: "Female",
    ip_address: "74.141.243.213",
  },
  {
    id: 2,
    first_name: "Ardis",
    last_name: "Wykey",
    email: "awykey1@bizjournals.com",
    gender: "Female",
    ip_address: "194.53.26.82",
  },
  {
    id: 3,
    first_name: "Jimmie",
    last_name: "Sheal",
    email: "jsheal2@nbcnews.com",
    gender: "Male",
    ip_address: "160.24.119.151",
  },
  {
    id: 4,
    first_name: "Elfie",
    last_name: "Blagdon",
    email: "eblagdon3@behance.net",
    gender: "Female",
    ip_address: "74.43.188.237",
  },
  {
    id: 5,
    first_name: "Linnet",
    last_name: "Melross",
    email: "lmelross4@nytimes.com",
    gender: "Female",
    ip_address: "132.33.231.18",
  },
  {
    id: 6,
    first_name: "Sunny",
    last_name: "Torri",
    email: "storri5@arstechnica.com",
    gender: "Male",
    ip_address: "177.104.63.226",
  },
  {
    id: 7,
    first_name: "Sholom",
    last_name: "Scarffe",
    email: "sscarffe6@google.fr",
    gender: "Male",
    ip_address: "0.241.9.147",
  },
  {
    id: 8,
    first_name: "Oran",
    last_name: "Bridie",
    email: "obridie7@sogou.com",
    gender: "Male",
    ip_address: "166.91.226.106",
  },
  {
    id: 9,
    first_name: "Skipton",
    last_name: "Sarney",
    email: "ssarney8@dropbox.com",
    gender: "Male",
    ip_address: "147.111.139.223",
  },
  {
    id: 10,
    first_name: "Dinny",
    last_name: "Duddin",
    email: "dduddin9@dedecms.com",
    gender: "Female",
    ip_address: "124.196.221.216",
  },
];
module.exports = students;
